# Generated by Django 5.0.7 on 2024-07-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.FloatField()),
                ('unite_de_mesure', models.CharField(blank=True, max_length=50, null=True)),
                ('prix_unitaire', models.FloatField()),
                ('seuil_alerte', models.FloatField(default=10)),
            ],
        ),
    ]
