# Generated by Django 5.0.7 on 2024-07-25 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='allergenes',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='description',
        ),
    ]
