# Generated by Django 5.0.7 on 2024-07-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_remove_plat_allergenes_remove_plat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commandeplat',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
