# Generated by Django 5.0.7 on 2024-07-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_alter_commande_montant_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='confirme',
            new_name='caissier_confirme',
        ),
    ]
