# Generated by Django 5.0.7 on 2024-07-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0005_category_plat_disponible_alter_plat_prix_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
