# Generated by Django 5.0.7 on 2024-07-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_commandeplat_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeplat',
            name='montant_plat_commande',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
