# Generated by Django 5.0.7 on 2024-07-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_commandeplat_montant_plat_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
