# Generated by Django 5.0.7 on 2024-07-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_commande_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Annulée', 'Annulée')], default='En attente', max_length=20),
        ),
    ]
