# Generated by Django 5.0.7 on 2024-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_commande_motif_annulation_alter_commande_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='responsable_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
