# Generated by Django 5.0.7 on 2024-08-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0011_commande_responsable_confirme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='responsable_confirme',
        ),
    ]
