# Generated by Django 5.0.7 on 2024-08-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_remove_commande_responsable_confirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(default='imgplat/default.jpg', upload_to='imgplat/'),
        ),
    ]
