# Generated by Django 5.0.7 on 2024-08-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0013_plat_description_plat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='image',
            field=models.ImageField(upload_to='imgplat/'),
        ),
    ]
