# Generated by Django 5.0.7 on 2024-07-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_default_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('caissier', 'Caissier'), ('comptable', 'Comptable'), ('responsable', 'Responsable'), ('client', 'Client')], max_length=20),
        ),
    ]
